backend:
  name: github
  repo: noiseatunsw/governance
  branch: main
  base_url: https://cms-auth.noiseatunsw.com/
media_folder: /static/media
public_folder: /media
publish_mode: editorial_workflow
collections:
  - name: "Minutes"
    label: "Minutes (T1 2025)"
    folder: "content/minutes/t1-2025"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "Conflicts of Interest Register"
    label: "Conflicts of Interest Register"
    folder: "content/conflicts-of-interest"
    create: true
    fields:
      - {label: "Name", name: "title", widget: "string"}
      - {label: "List", name: "body", widget: "markdown"}
